# Ch03 Numpy 數值計算

In [1]:
import numpy as np

In [3]:
# 版本確認
np.__version__

'1.23.5'

### Python List vs. NumPy Array 運算效能比較


In [4]:
# 計時測試，看 list 與 array 做出 0-9999999 所需時間差異

import numpy as np
import time

l1 = list(range(10000000))
l2 = list(range(10000000))
sum = []

then = time.time()
# list 直接相加，會變成後者 append 至前者
for i in range(len(l1)):
	sum.append(l1[i] + l2[i])

print(f"With just Python: {time.time() - then: .2f}s")

arr1 = np.array(l1)
arr2 = np.array(l2)

then = time.time()
sum = arr1 + arr2
print(f"With NumPy: {time.time() - then: .2f}s")

With just Python:  0.69s
With NumPy:  0.06s


### NumPy 迴圈操作和向量操作 數值運算效能比較


#### 迴圈操作

In [6]:
# 定義陣列元素取倒數輸出函式
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

In [7]:
# values random array
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.33333333, 0.11111111, 0.16666667, 0.2       ])

In [8]:
%timeit compute_reciprocals(values)

4.26 μs ± 17.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


#### 向量操作
_vector 效能完勝_

In [9]:
1.0 / values

array([0.11111111, 0.33333333, 0.11111111, 0.16666667, 0.2       ])

In [10]:
%timeit (1.0 / values)

544 ns ± 2.06 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## 向量運算 
_同 R，四則運算、次方直接做即可，vector 每個分量同步影響_

In [12]:
# 長度放大
ar = np.arange(0, 7) * 5; ar

array([ 0,  5, 10, 15, 20, 25, 30])

In [13]:
# 平方
ar = np.arange(5) ** 4 ; ar

array([  0,   1,  16,  81, 256])

In [14]:
# 開平方根
ar = np.arange(5) ** 0.5 ; ar

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [15]:
# 平移 
ar = 3 + np.arange(4); ar

array([3, 4, 5, 6])

#### Element-wise expression
_長度相等的向量做運算時，每項各自與對應者運算_

In [17]:
# 1D Array

arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([10, 20 , 30, 40])

arr_1 + arr_2 # [1 + 10, 2 + 20, 3 + 30, 4 + 40]


array([11, 22, 33, 44])

In [18]:
arr_1 * arr_2

array([ 10,  40,  90, 160])

In [19]:
arr_1 / arr_2

array([0.1, 0.1, 0.1, 0.1])

#### 維度相同者，運算規則比照長度辦理
_對應項目相加減乘除_

In [20]:
# 2D Array
arr = np.array([[1, 2], [3, 2]])
arr2 = np.array([[1, 6], [7, 8]])

In [21]:
arr * arr2

array([[ 1, 12],
       [21, 16]])

In [75]:
# Comparison operations
# 產 masking array (True / false)
arr < arr2

array([[False,  True],
       [ True,  True]])

In [22]:
arr != arr2

array([[False,  True],
       [ True,  True]])

#### 向量內積, 外積

In [25]:
# 向量內積 - 1D array (向量)
'''
內積在機器學習的領域，是很重要的概念，
無論是取得向量特徵，或是向量間的關係，
內積都扮演重要的角色

numpy.dot(a, b, /)

其它還有 
numpy.cross 叉積
numpy.outer 外積
可以自行嘗試
'''
arr1 = np.array([4, 5, 1, 3, 4])
arr2 = np.array([2, 3, 5, 4, 2])

'''
計算過程:
4*5 + 5*3 + 1*5 + 3*4 + 4*2 = 48
'''

inner_product = np.dot(arr1, arr2); inner_product


np.int64(48)

矩陣乘法運算，就是線性代數的乘法，以下圖為例:

![矩陣乘法運算](https://i.imgur.com/ItbwvTp.png)

計算過程:
![計算矩陣相乘](https://i.imgur.com/rOfh8yi.png)

參考資料: [线性代数基础——矩阵和矩阵的乘法](https://zhuanlan.zhihu.com/p/158776486)

In [26]:
# 向量內積 - 2D array (矩陣)

arr1 = np.array([[1, 0],[0, 1]])
arr2 = np.array([[4, 1],[2, 2]])

'''
計算過程 = 矩陣乘法 (pair-wise expression)
'''
inner_product = np.dot(arr1, arr2); inner_product

array([[4, 1],
       [2, 2]])

#### Outer product $\neq$ cross product (外積)
outer product: vectors 張成的張量 (tensor)

In [29]:
# Outer product - 1D array (向量) as 通式
arr1 = np.array(['a', 'b', 'c'], dtype = object)
np.outer(arr1,[1, 2, 3])

array([['a', 'aa', 'aaa'],
       ['b', 'bb', 'bbb'],
       ['c', 'cc', 'ccc']], dtype=object)

In [30]:
# Outer product - 1D array (向量)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

outer_product = np.outer(arr1, arr2); outer_product



array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [31]:
# Outer product - 2D array (向量) as 通式
arr1 = np.array([['a', 'b'], ['c', 'd']], dtype = object)
np.outer(arr1, [[1, 2], [3, 4]])

array([['a', 'aa', 'aaa', 'aaaa'],
       ['b', 'bb', 'bbb', 'bbbb'],
       ['c', 'cc', 'ccc', 'cccc'],
       ['d', 'dd', 'ddd', 'dddd']], dtype=object)

In [86]:
# Outer product - 2D array (矩陣)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[10, 20], [30, 40]])

outer_product = np.outer(arr1, arr2); outer_product

array([[ 10,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120],
       [ 40,  80, 120, 160]])

## 數學運算函式
* `.sum()`: vector 或 matrix 內所有數字加總 _可另用 axis 決定做 row sum 或 column sum_
* `.prod()`: 同上，改相乘
* `.diff()`: 同上，改後項減前項

In [32]:
arr = np.sum([1, 2, 3, 4])

# 一維陣列的「和」 (加總)
np.sum(arr)

np.int64(10)

In [35]:
arr_2 = np.sum([[1, 100], [12123, 4]])

# 二維陣列的「和」 (加總)
np.sum(arr_2)

np.int64(12228)

軸 (axis) 的概念
![軸 (axis) 的概念](https://i.imgur.com/u7ItSQZ.png)

參考資料: [Numpy Axes, Explained](https://youtu.be/aF96TC_6kDg)

In [36]:
# 二維陣列的「和」，指定軸 (axis) 來計算
'''
[
    [1, 2], 
    [3, 4], 
    [5, 6]
]

axis = None: 
- 所有元素，不分列 (row) 或行 (column)。預設值。
axis = 0:
- 順著 [0][0], [1][0], [2][0], ... 等索引號碼增加的方向
- 類似座標的 y 軸，針對每一個元素 y 軸對應的位置 (由上而下) 進行計算
axis = 1: 
- 順著 [0][0], [0][1], [0][2], ... 等索引號碼增加的方向
- 類似座標的 x 軸，針對每一個元素 x 軸對應的位置 (由左而右) 進行計算
'''
# 可用 axis 調整加總方式、方向
np.sum([[1, 2], [3, 4], [5, 6]], axis = 0) # [1+3+5, 2+4+6]

array([ 9, 12])

### 降維函式

In [90]:
# 一維陣列的「乘積」

np.prod([1, 2, 3, 4])

24

In [37]:
# 二維陣列的「乘積」
np.prod([[1, 5], [30, 4]])


np.int64(600)

In [39]:
# 二維陣列的「乘積」，指定軸 (axis) 來計算
'''
[
    [1,2], 
    [3,4], 
    [5,6]
]

axis = None: 
- 所有元素，不分列 (row) 或行 (column)。預設值。
axis = 0:
- 順著 [0][0], [1][0], [2][0], ... 等索引號碼增加的方向
- 類似座標的 y 軸，針對每一個元素 y 軸對應的位置 (由上而下) 進行計算
axis = 1: 
- 順著 [0][0], [0][1], [0][2], ... 等索引號碼增加的方向
- 類似座標的 x 軸，針對每一個元素 x 軸對應的位置 (由左而右) 進行計算
'''
# 沿 axis 1 (x 軸)算
np.prod([[1,2], [3,4], [5,6]], axis = 1)

array([ 2, 12, 30])

### 差值函式

In [41]:
# 一維陣列的「差」(後一個元素的值，減去前一個元素的值)
'''
numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
default axis = -1: 沿 x 軸往原點相減 (i.e. 後項減前項)
'''
x = np.array([7, 5, 3, 3, 9, 6, 7])
np.diff(x)

array([-2, -2,  0,  6, -3,  1])

In [49]:
# 一維陣列的「差」(指定 n，代表 diff 幾次)
np.diff(x, n = 2) # f''，後項減前項得 vector，再對該 vector 做一次 diff
# 等同 np.diff(np.diff(x))


array([ 0,  2,  6, -9,  4])

In [52]:
# 二維陣列的「差」，指定軸 (axis) 來計算
'''
[
    [1,2], 
    [3,4], 
    [5,6]
]

axis = None: 
- 所有元素，不分列 (row) 或行 (column)。預設值。
axis = 0:
- 順著 [0][0], [1][0], [2][0], ... 等索引號碼增加的方向
- 類似座標的 y 軸，針對每一個元素 y 軸對應的位置 (由上而下) 進行計算
axis = 1: 
- 順著 [0][0], [0][1], [0][2], ... 等索引號碼增加的方向
- 類似座標的 x 軸，針對每一個元素 x 軸對應的位置 (由左而右) 進行計算
'''
x = np.array([[1, 2], [3, 12], [5, 10]])
print(x)
# 沿 axis 0 (y 軸)做 diff，i.e. 下減上
np.diff(x, axis = 0)

[[ 1  2]
 [ 3 12]
 [ 5 10]]


array([[ 2, 10],
       [ 2, -2]])

### 捨去函式

In [54]:
# around(): 四捨五入到最近的「偶數值」
'''
numpy.around(被 around 者, decimals=0, out=None)

decimals: 指定小數位數 (小數點後面第幾位)，0 位開始
'''
np.around([0.45, 1.85], 1)

array([0.4, 1.8])

In [103]:
# rint(): 回傳最近的整數 (四捨五入到最近的「偶數值」)
np.rint([1.5, 2.5, 1.6, 3.3])

array([2., 2., 2., 3.])

In [55]:
# floor(): 無條件捨去
np.floor([1.5, 2.5, 1.6, 3.333])

array([1., 2., 1., 3.])

In [56]:
# ceil(): 無條件進位
np.ceil([1.1, 2.5, 1.6, 3.3])


array([2., 3., 2., 4.])

### 乘積函式

In [111]:
# 等價 arr1 * arr2
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[10, 20],[30, 40]])

np.multiply(arr1,arr2)

array([[ 10,  40],
       [ 90, 160]])

### 指數 & 對數 函式
* exponential
    * `.exp()`: euler number 的幾次方
    * `.exp${num}()`: 指定數字，i.e. 某數的幾次方
* logarithm
    * `.log()`: natural log
    * `.log${num}()`: 指定底數算對數    

In [57]:
# exp(): 自然對數 e 的幾次方
'''
e^1 = 2.71828183
e^2 = 7.3890561
e^3 = 20.08553692
e^4 = 54.59815003
.
.

'''
np.exp([1, 2, 3, 4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [58]:
# exp2(): 2 的幾次方
np.exp2([1, 2, 3, 4])

array([ 2.,  4.,  8., 16.])

In [59]:
# log(): 計算自然對數的值
'''
np.e = 自然對數

註: 
log(1) = 0 (任何數的 0 次方，等於 1)
log(e) = 1
log(e^2) = 2
'''
np.log([1, np.e, np.e ** 2])

array([0., 1., 2.])

In [60]:
# log2(): 計算以 2 為底的值
np.log2([1, 2, 4, 8])

array([0., 1., 2., 3.])

In [61]:
# log10(): 計算以 10 為底的值
np.log10([1, 10, 100, 1000])

array([0., 1., 2., 3.])

### Others
* `.absolute()`: get absolute value
* `.square()`: 取平方
* `.sqrt()`: 開根號

In [118]:
# absolute(): 回傳絕對值
np.absolute([-3, 3])

array([3, 3])

In [119]:
# square(): 回傳平方值
np.square([4, 9])

array([16, 81])

In [120]:
# sqrt(): 回傳平方根
np.sqrt([4, 9])

array([2., 3.])